
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`
umap_path: "data/04_features/umap.npy"
max_depth: 12
learning_rate: 0.01
n_jobs: 10
objective: "multi:softmax"
